server:
  port: 8080

#数据库配置
spring:
    redis:
      host:
      password:
      port:
      jedis:
        pool:
          max-active: 100
          max-wait: -1
          max-idle: 10
          min-idle: 0
      timeout: 10000



